### ISSUE TITLE
[REQUEST] --Flexible loss functions--

### ISSUE THREAD

**Issue by keeeto** [dmpelt/msdnet#17]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to use a loss function other than MSE for training or validation. 

**Describe the solution you'd like**
I think that two solutions could work
(i) Implementation of more loss functions
(ii) A simple guide on how users could write their own loss functions

There are pros and cons to each. Esentially flexibility vs off-the-shelf usability.

**Describe alternatives you've considered**
n/a

**Additional context**

We have been testing a number of networks for noise removal from microscopy images. One of our early findings is that if one uses a self similarity metric (SSIM) for network training then the result is a network that performs better on *all* metrics. I.e. a network trained with SSIM loss obtains a better MSE than a network trained with MSE loss. Therefore, we find that SSIM is the best loss functions for training our denoising networks.

We found the MSD performs almost as well as U-Net for denoising, despite the fact U-Net was trained with SSIM loss and MSD trained with MSE loss. So it is possible MSD could push even further. 

I also note that in cases where we used very few training examples MSD was the best performing network.

**Comment by dmpelt** [comment]
Thanks for opening this! I'm leaning towards a combination of (i) and (ii), in which some useful loss functions are already implemented and optimized, but also giving the ability for users to implement their own loss function through a Python function. What do you think about this plan? I'll have to find some time to work on it, but I'll put it on the top of my todo list -- I've always wanted this implemented!

Also thanks for the additional context! It is interesting to read about the fact that training for ssim gives better results for other metrics. I'm glad that MSD seems to work well for your data too!

**Comment by keeeto** [comment]
Thanks for the rapid response.

I think that a combo of (i) and (ii) is probably optimal. I guess that (i) is probably a bit easier to implement. But with such a zoo of loss functions out there it's hard to choose which ones you should do, although I guess there are some obvious ones. 

Of course I understand the time dilemma, but great to hear its on the todo list :)

**Comment by dmpelt** [comment]
@keeeto I've created an implementation in #19 . This includes the ability to define custom loss functions. As an example, see [here](https://github.com/dmpelt/msdnet/blob/fbb300c5b2cb97478975b9cd49fd9b14250eb38a/examples/train_regr_customloss.py). Is this roughly what you had in mind?

**Comment by dmpelt** [comment]
PS. I'd be happy to accept PRs to include useful loss functions in `loss.py` once #19 is accepted!

**Comment by dmpelt** [comment]
Implemented by #19
