### ISSUE TITLE
[BUG] --AttributeError while trying to run train_regr example code

### ISSUE THREAD

**Issue by Flubbynuggets** [dmpelt/msdnet#22]
**Describe the bug**
So, I have tried to run the example code for train_regr (Example 2) on a GPU enabled computer and my laptop, but whenever I run it, it produces the error:
![Error](https://user-images.githubusercontent.com/73121530/96464118-71de8400-11f5-11eb-9f2c-fc7f92cfb85b.JPG)

**To Reproduce**
I have not edited any of the code and am running the code on Jupyter Lab. The same error appeared when I tried running the code on Jupyter Notebook as well. I downloaded the MS-D Net line and I believe I installed the correct cuda-toolkit version.

To get this error, I ran generatedata, and then ran train_regr. The error popped up after running train_regr.

**Desktop:**
 - OS: Windows 10

I have tried tracing the error back to the train functions but there does not seem to be anything wrong with them. Again, I have not made any edits to the code yet, so I am not sure why it is not running.

**Comment by dmpelt** [comment]
Thanks for creating this issue! Can you try the following file: https://raw.githubusercontent.com/dmpelt/msdnet/master/examples/train_regr.py ? Some syntax has changed and maybe I didn't update all the examples correctly... In any case the error message has to be fixed so I'll try to do that soon!

**Comment by Flubbynuggets** [comment]
This worked! Thank you so much!
