### ISSUE TITLE
[INSTALLATION] Installing through conda-forge in Python 3.5

### ISSUE THREAD

**Issue by tomeramit** [dmpelt/msdnet#6]
**Describe the bug**
When trying to install with conda there are python package conflicts (my python is 3.5.4) also when tried to install over clean conda environment (python 3.5.4)
There is solution for that?

Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

  - astra-toolbox==1.8 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']
  - joblib==0.11 -> python[version='2.7.*,3.5.*,3.6.*']
  - keras==2.2.0 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
  - msdnet -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
  - numba==0.37.0 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']
  - numpy==1.13.1 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']
  - pandas==0.23.4 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
  - pywin32==220 -> python[version='2.7.*,3.4.*,3.5.*,3.6.*']
  - scikit-image==0.13.0 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']
  - scikit-learn==0.20.0 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
  - scipy==0.19.1 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']
  - semantic_version==2.6.0 -> python[version='2.7.*,3.4.*,3.5.*,3.6.*,>=3.7,<3.8.0a0']
  - theano==0.9.0 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']
  - tqdm==4.31.1 -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to.  Your current python version
is (python=3.5).  Note that conda will not change your python version to a different minor version
unless you explicitly specify that.

The following specifications were found to be incompatible with each other:

Package setuptools conflicts for:
pywin32==220 -> python[version='2.7.*,3.4.*,3.5.*,3.6.*'] -> pip -> wheel -> setuptools
scikit-learn==0.20.0 -> scipy -> numpy[version='1.11.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
joblib==0.11 -> python[version='2.7.*,3.5.*,3.6.*'] -> pip -> wheel -> setuptools
scikit-image==0.13.0 -> scipy[version='>=0.17'] -> numpy[version='1.11.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
semantic_version==2.6.0 -> python[version='2.7.*,3.4.*,3.5.*,3.6.*,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
tqdm==4.31.1 -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
theano==0.9.0 -> scipy[version='>=0.14,>=0.14.0'] -> numpy[version='1.10.*,1.11.*,1.9.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
numba==0.37.0 -> numpy[version='>=1.11.3,<2.0a0,>=1.13,<1.14.0a0,>=1.14,<1.15.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
python=3.5 -> pip -> wheel -> setuptools
pandas==0.23.4 -> numpy[version='>=1.11.*,>=1.11.3,<2.0a0,>=1.12.1,<2.0a0,>=1.14.6,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
keras==2.2.0 -> keras-base=2.2.0 -> keras-preprocessing==1.0.1 -> scipy[version='>=0.14'] -> numpy[version='1.10.*,1.11.*,1.9.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
numpy==1.13.1 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
astra-toolbox==1.8 -> scipy -> numpy[version='1.10.*,1.11.*,1.9.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
scipy==0.19.1 -> numpy[version='1.11.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
msdnet -> scikit-image -> scipy[version='>=0.17'] -> numpy[version='>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
plotly==3.2.1 -> requests -> urllib3[version='>=1.21.1,<1.22,>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.3,>=1.9,>=2.1.4,>=2.2.1'] -> cffi[version='>=1.4.1,>=1.7'] -> pycparser -> python[version='3.5.*,>=3.5,<3.6.0a0'] -> pip -> wheel -> setuptools
pip -> wheel -> setuptools
Package pip conflicts for:
numba==0.37.0 -> numpy[version='>=1.11.3,<2.0a0,>=1.13,<1.14.0a0,>=1.14,<1.15.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip
astra-toolbox==1.8 -> scipy -> numpy[version='1.10.*,1.11.*,1.9.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip
semantic_version==2.6.0 -> python[version='2.7.*,3.4.*,3.5.*,3.6.*,>=3.7,<3.8.0a0'] -> pip
scikit-learn==0.20.0 -> scipy -> numpy[version='1.11.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
msdnet -> scikit-image -> scipy[version='>=0.17'] -> numpy[version='>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
joblib==0.11 -> python[version='2.7.*,3.5.*,3.6.*'] -> pip
pywin32==220 -> python[version='2.7.*,3.4.*,3.5.*,3.6.*'] -> pip
scipy==0.19.1 -> numpy[version='1.11.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip
numpy==1.13.1 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip
scikit-image==0.13.0 -> scipy[version='>=0.17'] -> numpy[version='1.11.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip
keras==2.2.0 -> keras-base=2.2.0 -> keras-preprocessing==1.0.1 -> scipy[version='>=0.14'] -> numpy[version='1.10.*,1.11.*,1.9.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
python=3.5 -> pip
tqdm==4.31.1 -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
plotly==3.2.1 -> requests -> urllib3[version='>=1.21.1,<1.22,>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.3,>=1.9,>=2.1.4,>=2.2.1'] -> cffi[version='>=1.4.1,>=1.7'] -> pycparser -> python[version='3.5.*,>=3.5,<3.6.0a0'] -> pip
pandas==0.23.4 -> numpy[version='>=1.11.*,>=1.11.3,<2.0a0,>=1.12.1,<2.0a0,>=1.14.6,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
theano==0.9.0 -> scipy[version='>=0.14,>=0.14.0'] -> numpy[version='1.10.*,1.11.*,1.9.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip
Package six conflicts for:
msdnet -> scikit-image -> matplotlib[version='>=1.3.1,>=2.0.0'] -> python-dateutil -> six[version='>=1.5']
keras==2.2.0 -> keras-base=2.2.0 -> keras-preprocessing==1.0.1 -> six[version='>=1.9.0']
numba==0.37.0 -> singledispatch -> six
scikit-image==0.13.0 -> matplotlib[version='>=1.3.1,>=2.0.0'] -> python-dateutil -> six[version='>=1.5']
theano==0.9.0 -> pygpu[version='>=0.6.5,>=0.6.5,<0.7'] -> libgpuarray[version='0.6.8,0.6.9,0.7.0,0.7.1,0.7.3'] -> six
pandas==0.23.4 -> python-dateutil[version='>=2.5.*'] -> six[version='>=1.5']
astra-toolbox==1.8 -> six
plotly==3.2.1 -> requests -> urllib3[version='>=1.21.1,<1.22,>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.3,>=1.9,>=2.1.4,>=2.2.1'] -> six[version='>=1.4.1']
Package llvmlite conflicts for:
msdnet -> numba[version='>=0.41'] -> llvmlite[version='>=0.27.0,<0.28.0a0,>=0.28.0,<0.29.0a0,>=0.29.0,<0.30.0a0']
numba==0.37.0 -> llvmlite=0.22
Package wheel conflicts for:
keras==2.2.0 -> keras-base=2.2.0 -> keras-preprocessing==1.0.1 -> scipy[version='>=0.14'] -> numpy[version='1.10.*,1.11.*,1.9.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
python=3.5 -> pip -> wheel
numba==0.37.0 -> numpy[version='>=1.11.3,<2.0a0,>=1.13,<1.14.0a0,>=1.14,<1.15.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel
astra-toolbox==1.8 -> scipy -> numpy[version='1.10.*,1.11.*,1.9.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel
joblib==0.11 -> python[version='2.7.*,3.5.*,3.6.*'] -> pip -> wheel
tqdm==4.31.1 -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
pandas==0.23.4 -> numpy[version='>=1.11.*,>=1.11.3,<2.0a0,>=1.12.1,<2.0a0,>=1.14.6,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
pywin32==220 -> python[version='2.7.*,3.4.*,3.5.*,3.6.*'] -> pip -> wheel
scikit-image==0.13.0 -> scipy[version='>=0.17'] -> numpy[version='1.11.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel
scikit-learn==0.20.0 -> scipy -> numpy[version='1.11.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
pip -> wheel
semantic_version==2.6.0 -> python[version='2.7.*,3.4.*,3.5.*,3.6.*,>=3.7,<3.8.0a0'] -> pip -> wheel
numpy==1.13.1 -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel
plotly==3.2.1 -> requests -> urllib3[version='>=1.21.1,<1.22,>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.3,>=1.9,>=2.1.4,>=2.2.1'] -> cffi[version='>=1.4.1,>=1.7'] -> pycparser -> python[version='3.5.*,>=3.5,<3.6.0a0'] -> pip -> wheel
msdnet -> scikit-image -> scipy[version='>=0.17'] -> numpy[version='>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
theano==0.9.0 -> scipy[version='>=0.14,>=0.14.0'] -> numpy[version='1.10.*,1.11.*,1.9.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel
scipy==0.19.1 -> numpy[version='1.11.*,>=1.11.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel
Package psutil conflicts for:
scikit-image==0.13.0 -> dask[version='>=0.5'] -> distributed[version='>=1.19.0,>=1.20.0,>=1.21.0,>=1.23.2,>=1.28.0'] -> psutil
msdnet -> scikit-image -> dask[version='>=0.5'] -> distributed[version='>=1.19.0,>=1.20.0,>=1.21.0,>=1.23.2,>=1.28.0'] -> psutil
Package numba conflicts for:
msdnet -> numba[version='>=0.41']

**Comment by dmpelt** [comment]
Thanks for making this bug report.

I think conda-forge only builds packages for python 3.6 and 3.7 at the moment. Can you try to install inside a new 3.6 or 3.7 conda environment and see if you get the same error? You can create a new environment called `msdnettest` with the msdnet package installed by running:

```bash
conda create -n msdnettest -c conda-forge python=3.7 msdnet
```

If you want other python packages installed in the same environment, you can add them to the list at the end (e.g. ipython, matplotlib). Afterwards, you can run the following to activate the new environment:

```bash
conda activate msdnettest
```

Inside the new environment, you can check whether the msdnet package is correctly installed by running `python -c "import msdnet"`. If this doesn't give any errors, the package is correctly installed!

If you want to install msdnet inside your existing 3.5 environment, I guess the easiest way to do this is to clone/download the github repository, and run `python setup.py install`. For this you need to have the build-time dependencies of msdnet installed, which you can try through conda:

```bash
conda install -c conda-forge setuptools scikit-build openmp
```

Note that you also need the runtime depencies installed, which you can try through conda:

```bash
conda install -c conda-forge numpy tifffile scikit-image psutil h5py tqdm numba cudatoolkit imageio openmp
```

If you get any package conflict errors during the installation of the dependencies, I guess that there is an actual version conflict somewhere in the system (e.g. msdnet relies on a certain version of a package, while an already installed package needs a different version). This will probably be hard to fix -- in this case I would recommend installing msdnet in a separate conda environment.

**Comment by tomeramit** [comment]
It worked! thanks!
suggesting to write the python version as well in the read me file!
